version: '3.8'

services:
  i2m:
    build:
      context: .
      dockerfile: Dockerfile_i2m
    ports:
      - "4441:7860"
      - "4442:8000"
      - "4443:9100"
    environment:
      - HF_API_TOKEN=${HF_API_TOKEN}
    networks:
      - group17_i2m
      

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_vol:/prometheus  
      - ./prometheus.yml:/etc/prometheus/prometheus.yml 
    ports:
      - "4444:9090"  
    networks:
      - group17_i2m

  grafana:
    image: grafana/grafana:latest
    ports:
      - "4445:3000" 
    networks:
      - group17_i2m
    volumes:
      - grafana_vol:/var/lib/grafana

networks:
  group17_i2m:
    driver: bridge

volumes:
  grafana_vol:
  prometheus_vol:  
